import subprocess
import sys
from io import StringIO
from pathlib import Path
from typing import Any

import pytest
from django.core.management import call_command
from django.core.management.base import CommandError

from tests.catalogue import catalogue
from tunables import Catalogue, Float, Group, Tunable
from tunables.errors import CatalogueError
from tunables.export import keys_module

EXPECTED = '''"""Tunable keys, generated by tunables_export --keys. Do not edit."""

# pricing
PRICING_VAT_RATE = "pricing.vat_rate"
PRICING_FREE_SHIPPING_OVER = "pricing.free_shipping_over"
PRICING_CURRENCIES = "pricing.currencies"
PRICING_SHIPPING_RATES = "pricing.shipping_rates"
PRICING_ALLOW_BACKORDERS = "pricing.allow_backorders"

# thermostat
THERMOSTAT_TARGET_C = "thermostat.target_c"
THERMOSTAT_MODE = "thermostat.mode"
THERMOSTAT_SAMPLE_INTERVAL = "thermostat.sample_interval"
THERMOSTAT_DISPLAY_COLOUR = "thermostat.display_colour"
THERMOSTAT_LEGACY_OFFSET = "thermostat.legacy_offset"

# weights
WEIGHTS_ALPHA = "weights.alpha"
WEIGHTS_BETA = "weights.beta"
WEIGHTS_GAMMA = "weights.gamma"

# limits
LIMITS_MAX_CURRENCIES = "limits.max_currencies"

ALL_KEYS: tuple[str, ...] = (
    PRICING_VAT_RATE,
    PRICING_FREE_SHIPPING_OVER,
    PRICING_CURRENCIES,
    PRICING_SHIPPING_RATES,
    PRICING_ALLOW_BACKORDERS,
    THERMOSTAT_TARGET_C,
    THERMOSTAT_MODE,
    THERMOSTAT_SAMPLE_INTERVAL,
    THERMOSTAT_DISPLAY_COLOUR,
    THERMOSTAT_LEGACY_OFFSET,
    WEIGHTS_ALPHA,
    WEIGHTS_BETA,
    WEIGHTS_GAMMA,
    LIMITS_MAX_CURRENCIES,
)
'''


def run(*args: str) -> str:
    out = StringIO()
    call_command("tunables_export", *args, stdout=out)
    return out.getvalue()


def formatted(text: str, tmp_path: Path) -> str:
    target = tmp_path / "keys.py"
    target.write_text(text)
    result = subprocess.run(
        [sys.executable, "-m", "ruff", "format", "--line-length", "120", str(target)],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, result.stderr
    return target.read_text()


def test_the_text_is_exactly_this() -> None:
    assert keys_module(catalogue) == EXPECTED


def test_the_formatter_leaves_it_alone(tmp_path: Path) -> None:
    text = keys_module(catalogue)
    assert formatted(text, tmp_path) == text


def test_the_module_executes_and_matches_the_catalogue() -> None:
    namespace: dict[str, Any] = {}
    exec(compile(keys_module(catalogue), "keys.py", "exec"), namespace)  # noqa: S102
    assert namespace["ALL_KEYS"] == tuple(catalogue.keys())
    assert namespace["PRICING_VAT_RATE"] == "pricing.vat_rate"
    assert namespace["LIMITS_MAX_CURRENCIES"] == "limits.max_currencies"


def test_an_empty_catalogue_emits_one_line(tmp_path: Path) -> None:
    text = keys_module(Catalogue([]))
    assert text.endswith("ALL_KEYS: tuple[str, ...] = ()\n")
    assert "(\n)" not in text
    assert formatted(text, tmp_path) == text


def test_a_group_with_one_tunable_still_lists_it() -> None:
    small = Catalogue([Group("limits", [Tunable("max_currencies", Float(), 3.0)])])
    assert '# limits\nLIMITS_MAX_CURRENCIES = "limits.max_currencies"\n' in keys_module(small)


def test_colliding_constant_names_are_rejected() -> None:
    clashing = Catalogue(
        [
            Group("pricing", [Tunable("vat_rate", Float(), 0.2)]),
            Group("pricing_vat", [Tunable("rate", Float(), 0.2)]),
        ]
    )
    with pytest.raises(CatalogueError, match="PRICING_VAT_RATE"):
        keys_module(clashing)


def test_a_one_key_module_survives_the_formatter(tmp_path: Path) -> None:
    small = Catalogue([Group("limits", [Tunable("max_currencies", Float(), 3.0)])])
    text = keys_module(small)
    assert text.endswith("ALL_KEYS: tuple[str, ...] = (LIMITS_MAX_CURRENCIES,)\n")
    assert formatted(text, tmp_path) == text


def test_a_key_cannot_shadow_all_keys() -> None:
    reserved = Catalogue([Group("all", [Tunable("keys", Float(), 1.0)])])
    with pytest.raises(CatalogueError, match="ALL_KEYS"):
        keys_module(reserved)


def test_the_command_writes_the_module(db: None, tmp_path: Path) -> None:
    target = tmp_path / "keys.py"
    assert run("--keys", "--output", str(target)) == f"wrote {target}\n"
    assert target.read_text() == EXPECTED
    assert run("--keys") == EXPECTED


def test_the_command_rejects_combining_outputs(db: None) -> None:
    for pair in (("--keys", "--defaults"), ("--keys", "--schema")):
        with pytest.raises(CommandError, match="cannot be combined"):
            run(*pair)


def test_the_generator_runs_with_no_django_settings() -> None:
    import os

    script = Path(__file__).parent / "offline_keys.py"
    env = {k: v for k, v in os.environ.items() if k != "DJANGO_SETTINGS_MODULE"}
    result = subprocess.run([sys.executable, str(script)], capture_output=True, text=True, env=env)
    assert result.returncode == 0, result.stderr
    assert 'PRICING_VAT_RATE = "pricing.vat_rate"' in result.stdout
    assert result.stdout.endswith("ALL_KEYS: tuple[str, ...] = (PRICING_VAT_RATE,)\n")
