"""Generate source files from a catalogue. No Django settings and no database."""

from tunables.catalogue import Catalogue
from tunables.errors import CatalogueError

HEADER = '"""Tunable keys, generated by tunables_export --keys. Do not edit."""'
TUPLE_NAME = "ALL_KEYS"


def keys_module(catalogue: Catalogue) -> str:
    """A Python module of key constants, grouped by group, plus ALL_KEYS.

    The text is already formatted, so a host's formatter leaves it alone.
    """
    lines = [HEADER]
    names: dict[str, str] = {}
    for group in catalogue.groups.values():
        lines.append("")
        lines.append(f"# {group.name}")
        for tunable in group.tunables:
            key = f"{group.name}.{tunable.name}"
            name = _constant(key)
            if name == TUPLE_NAME:
                raise CatalogueError(f"key {key!r} produces {TUPLE_NAME}, the name the module gives the key tuple")
            if name in names:
                raise CatalogueError(f"keys {names[name]!r} and {key!r} both produce the constant {name}")
            names[name] = key
            lines.append(f'{name} = "{key}"')
    lines.append("")
    if len(names) > 1:
        lines.append(f"{TUPLE_NAME}: tuple[str, ...] = (")
        # A trailing comma keeps one name per line whatever the formatter's line length.
        lines.extend(f"    {name}," for name in names)
        lines.append(")")
    else:
        # A one-element tuple needs its comma, so a formatter collapses it to one line anyway.
        inner = f"{next(iter(names))}," if names else ""
        lines.append(f"{TUPLE_NAME}: tuple[str, ...] = ({inner})")
    return "\n".join(lines) + "\n"


def _constant(key: str) -> str:
    """PRICING_VAT_RATE for pricing.vat_rate."""
    return key.replace(".", "_").upper()
