# Generated by Django 6.1 on 2026-08-30 16:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("actor", models.CharField(max_length=255)),
                (
                    "actor_source",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("asserted", "Asserted"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                ("client", models.CharField(blank=True, max_length=255)),
                ("reason", models.TextField(blank=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("api", "Api"),
                            ("import", "Import"),
                            ("rollback", "Rollback"),
                            ("system", "System"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "restores_version",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("request_id", models.CharField(blank=True, max_length=255)),
                ("catalogue_version", models.CharField(max_length=80)),
                ("metadata", models.JSONField(default=dict)),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="TunableDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("group_name", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=100)),
                ("order", models.IntegerField()),
                ("type_name", models.CharField(max_length=100)),
                ("type_params", models.JSONField()),
                ("default", models.JSONField()),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("unit", models.CharField(blank=True, max_length=255)),
                ("ui", models.JSONField(default=dict)),
                ("metadata", models.JSONField(default=dict)),
                ("deprecated", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("synced_at", models.DateTimeField()),
            ],
            options={
                "ordering": ["group_name", "order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.PositiveIntegerField(unique=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("format_version", models.PositiveSmallIntegerField()),
                ("catalogue_version", models.CharField(max_length=80)),
                ("document", models.JSONField()),
                (
                    "changeset",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tunables.changeset",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False),
                ),
                ("current_version", models.PositiveIntegerField(default=0)),
                ("catalogue_version", models.CharField(blank=True, max_length=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(condition=models.Q(("id", 1)), name="tunables_state_single_row")
                ],
            },
        ),
        migrations.CreateModel(
            name="TunableValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.JSONField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "changeset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tunables.changeset",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tunables.tunabledefinition",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=255)),
                ("old_value", models.JSONField(blank=True, null=True)),
                ("new_value", models.JSONField(blank=True, null=True)),
                ("reset", models.BooleanField(default=False)),
                (
                    "changeset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="tunables.changeset",
                    ),
                ),
                (
                    "definition",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="tunables.tunabledefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("changeset", "key"),
                        name="tunables_changeitem_unique_key",
                    )
                ],
            },
        ),
    ]
