# Generated by Django 6.1.1 on 2026-09-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tunables", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublisherState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("publisher", models.CharField(max_length=255, unique=True)),
                ("last_version", models.PositiveIntegerField(blank=True, null=True)),
                ("last_published_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
