# Generated by Django 6.1.1 on 2026-09-18 19:41

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tunables", "0002_publisherstate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        unique=True,
                        validators=[django.core.validators.RegexValidator("^[a-z0-9][a-z0-9_-]*$")],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("from_catalogue", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name="tunabledefinition",
            name="category_name",
            field=models.CharField(default="general", max_length=100),
        ),
        migrations.CreateModel(
            name="TunableDefinitionTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("seeded", models.BooleanField(default=False)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tunables.tunabledefinition",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="tunables.tag"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="tunabledefinition",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="definitions",
                through="tunables.TunableDefinitionTag",
                to="tunables.tag",
            ),
        ),
        migrations.AddConstraint(
            model_name="tunabledefinitiontag",
            constraint=models.UniqueConstraint(fields=("definition", "tag"), name="tunables_definitiontag_unique"),
        ),
    ]
