# Generated by Django 6.1.1 on 2026-09-21 20:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tunables", "0003_categories_and_tags"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tunabledefinition",
            options={
                "ordering": ["group_name", "order", "name"],
                "verbose_name": "tunable",
                "verbose_name_plural": "tunables",
            },
        ),
    ]
