# Generated by Django 6.1.1 on 2026-09-21 21:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tunables", "0004_alter_tunabledefinition_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunabledefinitiontag",
            name="assigned_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tunabledefinitiontag",
            name="assigned_by",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
