# Generated by Django 6.1.1 on 2026-09-21 21:35

from typing import Any

import django.utils.timezone
from django.db import migrations, models


def mark_seeded_rows(apps: Any, _schema_editor: Any) -> None:
    """Rows seeded before this migration came from tunables_sync, so they are the system's."""
    apps.get_model("tunables", "TunableDefinitionTag").objects.filter(seeded=True).update(assigned_by="system")


class Migration(migrations.Migration):
    dependencies = [
        ("tunables", "0004_alter_tunabledefinition_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tunabledefinitiontag",
            name="assigned_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="tunabledefinitiontag",
            name="assigned_by",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.RunPython(mark_seeded_rows, migrations.RunPython.noop),
    ]
